// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Echoes Of The Pantanal",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Echoes Of The Pantanal",
            targets: ["AppModule"],
            bundleIdentifier: "me.alencar.jose.Echoes-Of-The-Pantanal",
            teamIdentifier: "NN9GWC737D",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            additionalInfoPlistContentFilePath: "Info.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Sounds")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)